### ISSUE TITLE
Sparkfun RTK Express RTCM ver

### ISSUE THREAD

**Issue by BeniDodelson** [sparkfun/SparkFun_RTK_Express#2]
Hi,

I wonder if RTK Express supports RTCM ver 3.2 and/or what ver. it supports?

Tx.

**Comment by nseidle** [comment]
Yep. Please see the 'Default interface settings' in the [integration manual](https://www.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_UBX-18010802.pdf)

> RTCM 3.3 is the default input and output protocol

![image](https://user-images.githubusercontent.com/117102/132711627-4a97f7e0-36ab-4cf2-b3bc-ffb322185299.png)

**Comment by BeniDodelson** [comment]
Tx. Nathan.
 
Appreciate your help.
 
Beni.
 
Beni Dodelson
G.P.Co. Trade Ltd.

20b Ha’Gome St.
POB 4187
Kadima
Israel 6092000
 
Tel : +972 - (0)54 - 5707979
Fax: +972 – (0) 9 – 8992284
E_mail :  ***@***.***> ***@***.***
