### ISSUE TITLE
add another button to the overlay

### ISSUE THREAD

**Issue by mzandrew** [sparkfun/SparkFun_RTK_Express#5]
It would be nice to have an extra button (or two) for the interface.  Something to add the ability to mark multiple types of thing during a single survey (think button "A" for fenceposts vs button "B" for treestumps).  Or could mark the beginning and end of tracks (think press "A"; perambulate one's yard; press "A" again; move to backyard; repeat; end up with two tracks marking out yards).  Button "B" could close file and open another one to further aid in doing complicated surveys.

An extra button or two could also add functionality to various menus.

Looks like there's two spare pins on the connector that could be used, so one button probably wouldn't be a big deal to add (without forgoing the pin doubling or changing the connector type).  Would need to modify the main board to accommodate this of course.

**Comment by nseidle** [comment]
Hi! Thanks for the idea contribution. For now we plan to keep the device as simple as possible and leave the user interactions to the tablet or cellphone to record points of interest.
